### ISSUE TITLE
Duration Validation

### ISSUE THREAD

**Issue by HughP** [HughP/Supporting-Evidence-for-OLAC-and-Learning-Resources#3]
@MattGyverLee

I started looking into date validation there is a regex [here](https://regex101.com/library/bT0wL2?%21%5CS&orderBy=LEAST_POINTS&page=743), some situational discussion [here](https://docstore.mik.ua/orelly/xml/schema/ch04_05.htm) and [here](https://www.oreilly.com/library/view/regular-expressions-cookbook/9781449327453/ch04s07.html). And a really helpful [stackoverflow](https://stackoverflow.com/questions/32044846/regex-for-iso-8601-durations)...

Two Points: 

1. Using ISO8601 is required by LRMI therefore I do not think we can rely on XSD date type validation and should not convert these values, rather they should be treated as strings.
2. I don't have a set of test cases to validate the linked regex.

**Comment by MattGyverLee** [comment]
The regexes I found all had lookarounds, which are not valid in XSDs. I instead used the standard xs:duration type.

**Comment by HughP** [comment]
This is great progress. I wonder if those hacks were just always invalid or
the difference between 1.0 and 1.1?

Which documentation are you referring to?

https://www.w3.org/TR/xmlschema-2/#deviantformats

https://www.w3.org/TR/xmlschema/#duration

**Comment by MattGyverLee** [comment]
All of the top-rated options on the StackOverflow (that was what I had found) had lookarounds.
![image](https://user-images.githubusercontent.com/986339/194138264-38002450-e382-45d9-86f7-7e0fe7804bb3.png)

This [one](https://regex101.com/library/bT0wL2?%21%5CS&orderBy=LEAST_POINTS&page=743
) only matches if there is a T:
![image](https://user-images.githubusercontent.com/986339/194139979-70026574-5d84-46fb-ba6f-7e4f0d37b221.png) and would match the invalid "PT". 

I think we can just let XML validate it as a [duration](https://www.w3.org/TR/xmlschema/#duration) which is linked back to ISO 8601.
